#!/bin/bash

/usr/sbin/groupadd -g 202 system_fw
/usr/sbin/groupadd -g 251 web_fw
/usr/sbin/groupadd -g 301 app_fw
/usr/sbin/groupadd -g 402 security_fw
/usr/sbin/groupadd -g 451 multimedia_fw
/usr/sbin/groupadd -g 501 graphic_fw
/usr/sbin/groupadd -g 502 ui_fw
/usr/sbin/groupadd -g 551 network_fw
/usr/sbin/groupadd -g 601 telephony
/usr/sbin/groupadd -g 651 service_fw
/usr/sbin/groupadd -g 652 messaging
/usr/sbin/groupadd -g 653 social
/usr/sbin/groupadd -g 654 location
/usr/sbin/groupadd -g 655 sensor
/usr/sbin/groupadd -g 901 sdk
/usr/sbin/groupadd -g 925 scm
/usr/sbin/groupadd -g 951 application
/usr/sbin/groupadd -g 1001 broadcasting
/usr/sbin/groupadd -g 1026 testing
/usr/sbin/groupadd -g 1051 system_share

/usr/sbin/useradd system_fw -u 202 -g 202 -d /var/lib/empty -s /sbin/nologin -c "system framework"
/usr/sbin/useradd web_fw -M -u 251 -g 251 -d /var/lib/empty -s /sbin/nologin -c "web framework"
/usr/sbin/useradd app_fw -M -u 301 -g 301 -d /var/lib/empty -s /sbin/nologin -c "app framework"
/usr/sbin/useradd security_fw -M -u 402 -g 402 -d /var/lib/empty -s /sbin/nologin -c "security framework"
/usr/sbin/useradd multimedia_fw -M -u 451 -g 451 -d /var/lib/empty -s /sbin/nologin -c "multimedia framework"
/usr/sbin/useradd graphic_fw -M -u 501 -g 501 -d /var/lib/empty -s /sbin/nologin -c "graphic framework"
/usr/sbin/useradd ui_fw -M -u 502 -g 502 -d /var/lib/empty -s /sbin/nologin -c "ui framework"
/usr/sbin/useradd network_fw -M -u 551 -g 551 -d /var/lib/empty -s /sbin/nologin -c "network framework"
/usr/sbin/useradd telephony -M -u 601 -g 601 -d /var/lib/empty -s /sbin/nologin -c "telephony"
/usr/sbin/useradd service_fw -M -u 651 -g 651 -d /var/lib/empty -s /sbin/nologin -c "messaging"
/usr/sbin/useradd messaging -M -u 652 -g 652 -d /var/lib/empty -s /sbin/nologin -c "web framework"
/usr/sbin/useradd social -M -u 653 -g 653 -d /var/lib/empty -s /sbin/nologin -c "social"
/usr/sbin/useradd location -M -u 654 -g 654 -d /var/lib/empty -s /sbin/nologin -c "location"
/usr/sbin/useradd sensor -M -u 655 -g 655 -d /var/lib/empty -s /sbin/nologin -c "sensor"
/usr/sbin/useradd sdk -M -u 901 -g 901 -d /var/lib/empty -s /sbin/nologin -c "sdk"
/usr/sbin/useradd scm -M -u 925 -g 925 -d /var/lib/empty -s /sbin/nologin -c "scm"
/usr/sbin/useradd application -M -u 951 -g 951 -d /var/lib/empty -s /sbin/nologin -c "application"
/usr/sbin/useradd broadcasting -M -u 1001 -g 1001 -d /var/lib/empty -s /sbin/nologin -c "broadcasting"
/usr/sbin/useradd testing -M -u 1026 -g 1026 -d /var/lib/empty -s /sbin/nologin -c "testing"
/usr/sbin/useradd system_share -M -u 1051 -g 1051 -d /var/lib/empty -s /sbin/nologin -c "system_share"

/usr/sbin/groupmod -A system_fw system_share
/usr/sbin/groupmod -A web_fw system_share
/usr/sbin/groupmod -A app_fw system_share
/usr/sbin/groupmod -A security_fw system_share
/usr/sbin/groupmod -A multimedia_fw system_share
/usr/sbin/groupmod -A graphic_fw system_share
/usr/sbin/groupmod -A ui_fw system_share
/usr/sbin/groupmod -A network_fw system_share
/usr/sbin/groupmod -A telephony system_share
/usr/sbin/groupmod -A service_fw system_share
/usr/sbin/groupmod -A messaging system_share
/usr/sbin/groupmod -A social system_share
/usr/sbin/groupmod -A location system_share
/usr/sbin/groupmod -A sensor system_share
/usr/sbin/groupmod -A sdk system_share
/usr/sbin/groupmod -A scm system_share
/usr/sbin/groupmod -A application system_share
/usr/sbin/groupmod -A broadcasting system_share
/usr/sbin/groupmod -A testing system_share
/usr/sbin/groupmod -A buxton system_share
/usr/sbin/groupmod -A key-manager system_share
/usr/sbin/groupmod -A cynara system_share
/usr/sbin/groupmod -A dbus system_share
/usr/sbin/groupmod -A pulse system_share
