#!/bin/bash

if [ ! -e /opt/data/.security_config_tmp ]; then
    /bin/touch /opt/data/.security_config_tmp
fi

/usr/sbin/useradd system_fw -u 202
/usr/sbin/useradd web_fw -u 251
/usr/sbin/useradd app_fw -u 301
/usr/sbin/useradd security_fw -u 402
/usr/sbin/useradd multimedia_fw -u 451
/usr/sbin/useradd graphic_fw -u 501
/usr/sbin/useradd ui_fw -u 502
/usr/sbin/useradd network_fw -u 551
/usr/sbin/useradd telephony -u 601
/usr/sbin/useradd service_fw -u 651
/usr/sbin/useradd messaging -u 652
/usr/sbin/useradd social -u 653
/usr/sbin/useradd location -u 654
/usr/sbin/useradd sdk -u 901
/usr/sbin/useradd scm -u 925
/usr/sbin/useradd application -u 951
/usr/sbin/useradd broadcasting -u 1001
/usr/sbin/useradd testing -u 1026
/usr/sbin/useradd system_share -u 1051

/usr/sbin/usermod -s /sbin/false system_fw
/usr/sbin/usermod -s /sbin/false web_fw
/usr/sbin/usermod -s /sbin/false app_fw
/usr/sbin/usermod -s /sbin/false security_fw
/usr/sbin/usermod -s /sbin/false multimedia_fw
/usr/sbin/usermod -s /sbin/false graphic_fw
/usr/sbin/usermod -s /sbin/false ui_fw
/usr/sbin/usermod -s /sbin/false network_fw
/usr/sbin/usermod -s /sbin/false telephony
/usr/sbin/usermod -s /sbin/false service_fw
/usr/sbin/usermod -s /sbin/false messaging
/usr/sbin/usermod -s /sbin/false social
/usr/sbin/usermod -s /sbin/false location
/usr/sbin/usermod -s /sbin/false sdk
/usr/sbin/usermod -s /sbin/false scm
/usr/sbin/usermod -s /sbin/false application
/usr/sbin/usermod -s /sbin/false broadcasting
/usr/sbin/usermod -s /sbin/false testing
/usr/sbin/usermod -s /sbin/false system_share

/usr/sbin/groupadd -g 202 system_fw
/usr/sbin/groupadd -g 251 web_fw
/usr/sbin/groupadd -g 301 app_fw
/usr/sbin/groupadd -g 402 security_fw
/usr/sbin/groupadd -g 451 multimedia_fw
/usr/sbin/groupadd -g 501 graphic_fw
/usr/sbin/groupadd -g 502 ui_fw
/usr/sbin/groupadd -g 551 network_fw
/usr/sbin/groupadd -g 601 telephony
/usr/sbin/groupadd -g 651 service_fw
/usr/sbin/groupadd -g 652 messaging
/usr/sbin/groupadd -g 653 social
/usr/sbin/groupadd -g 654 location
/usr/sbin/groupadd -g 901 sdk
/usr/sbin/groupadd -g 925 scm
/usr/sbin/groupadd -g 951 application
/usr/sbin/groupadd -g 1001 broadcasting
/usr/sbin/groupadd -g 1026 testing
/usr/sbin/groupadd -g 1051 system_share

/usr/sbin/groupmod -A system_fw system_share
/usr/sbin/groupmod -A web_fw system_share
/usr/sbin/groupmod -A app_fw system_share
/usr/sbin/groupmod -A security_fw system_share
/usr/sbin/groupmod -A multimedia_fw system_share
/usr/sbin/groupmod -A graphic_fw system_share
/usr/sbin/groupmod -A ui_fw system_share
/usr/sbin/groupmod -A network_fw system_share
/usr/sbin/groupmod -A telephony system_share
/usr/sbin/groupmod -A service_fw system_share
/usr/sbin/groupmod -A messaging system_share
/usr/sbin/groupmod -A social system_share
/usr/sbin/groupmod -A location system_share
/usr/sbin/groupmod -A sdk system_share
/usr/sbin/groupmod -A scm system_share
/usr/sbin/groupmod -A application system_share
/usr/sbin/groupmod -A broadcasting system_share
/usr/sbin/groupmod -A testing system_share