#!/bin/bash

## Setting capability in binary image creation stage(via mic)

# Package		sdbd
# Required		cap_setuid, cap_setgid
# cap_setuid		set user id per each user logged in
# cap_setgid		set group id following user id

/usr/sbin/setcap cap_setuid,cap_setgid=eip /usr/sbin/sdbd

# Package		alarm-server
# Required		cap_sys_time
# cap_sys_time		settimeofday() system call and rtc setting time need privilege; CAP_SYS_TIME

/usr/sbin/setcap cap_sys_time=eip /usr/bin/alarm-server

# Package		download-provider
# Required		cap_dac_override
# cap_dac_override	needs to access directory which user id is different (override DAC permission)

/usr/sbin/setcap cap_dac_override=eip /usr/bin/download-provider
